### ISSUE TITLE
Possible angles of investigation for slowness on rpi4

### ISSUE THREAD

**Issue by koenusz** [ScenicFramework/scenic_driver_local#24]
I am trying to get scenic to work on rpi4 with nerves. I got it to work somewhat but a few issues remain. During my investigation I stumbled onto two comments that might provide some leads for investigating the performance issues when running scenic on rpi4. Hope my observations are of any help.

When plugging in my 7" display into my rpi4 with nerves I was getting bad performance without even having scenic added to my application. This to me suggests that the issue is indeed with the hardware setup and not necessarily related to scenic. Disabling the vc4-kms-v3d driver in config.txt solved this issue but obviously this did not allow me to run scenic anymore.

I found an interesting comment on the [raspberri pi forum](https://forums.raspberrypi.com//viewtopic.php?t=243707#p1503909). Here they suggest that the opengl context might be using the llvmpipe software rasterizer under the hood and not the vc4/v3d GPU driver. I was not able to confirm this.

I found an  [article](https://blogs.igalia.com/itoral/2023/02/20/supertuxkart-vulkan-vs-opengl-and-zink-status-on-raspberry-pi-4/#comment-26332)  that talks about a compatibility mode in the mesa driver that tanslated rgba16f to its 32 bit counterpart putting a lot of strain on the cpu. Considering the issues seem to be present without scenic this does not sound like a likely cause.

For a bit of context:

I needed to update the driver and recompile the code. Supposedly the /dev/dri/card0 is used by the v3d-drm driver and the vc4-drm driver is using the /dev/dri/card1. I read that not on every device this assignment is guaranteed. So perhaps it whould be wise to first try the one and if that fails try the other.

The second issue is that the vc4-drm driver does not initialize until after I physically plug in a device into the usb. This causes the scenic_driver_local to crash. (the /dev/dri/card1 is not available so the call to open causes a crash) After I plug in the device and restart the application the drivers starts up normally.

<details>
<summary>Log file summary</summary>

``` 14:53:19.559 [info] input: USB GAMING MOUSE  as /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/0003:18F8:1286.0002/input/input2

14:53:19.559 [info] hid-generic 0003:18F8:1286.0002: input,hidraw1: USB HID v1.10 Mouse [USB GAMING MOUSE ] on usb-0000:01:00.0-1.3/input0

14:53:19.559 [info] vc4-drm gpu: bound fe400000.hvs (ops vc4_drm_unregister [vc4])

14:53:19.566 [info] vc4-drm gpu: bound fef00700.hdmi (ops vc4_drm_unregister [vc4])

14:53:19.566 [info] input: USB GAMING MOUSE  Keyboard as /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.1/0003:18F8:1286.0003/input/input3

14:53:19.566 [info] vc4-drm gpu: bound fef05700.hdmi (ops vc4_drm_unregister [vc4])

14:53:19.567 [info] vc4-drm gpu: bound fe004000.txp (ops vc4_drm_unregister [vc4])

14:53:19.571 [info] vc4-drm gpu: bound fe206000.pixelvalve (ops vc4_drm_unregister [vc4])

14:53:19.571 [info] vc4-drm gpu: bound fe207000.pixelvalve (ops vc4_drm_unregister [vc4])

14:53:19.571 [info] vc4-drm gpu: bound fe20a000.pixelvalve (ops vc4_drm_unregister [vc4])

14:53:19.571 [info] vc4-drm gpu: bound fe216000.pixelvalve (ops vc4_drm_unregister [vc4])

14:53:19.571 [info] vc4-drm gpu: bound fec12000.pixelvalve (ops vc4_drm_unregister [vc4])

14:53:19.571 [info] [drm] Initialized vc4 0.0.0 20140616 for gpu on minor 1

14:53:19.630 [info] hid-generic 0003:18F8:1286.0003: input,hiddev97,hidraw2: USB HID v1.10 Keyboard [USB GAMING MOUSE ] on usb-0000:01:00.0-1.3/input1

14:53:19.646 [info] Console: switching to colour frame buffer device 128x48

14:53:19.670 [info] vc4-drm gpu: [drm] fb0: vc4drmfb frame buffer device

14:54:05.302 [info] usb 1-1.3: USB disconnect, device number 4 ```
<details>

**Comment by ringlej** [comment]
You might give the cairo driver that is now on `main` a whirl. It should work well on the rpi4

**Comment by koenusz** [comment]
Thank you, I will do that

**Comment by koenusz** [comment]
Seems to work quite ok, my app boots into scenic. and seems responsive. I ran into a weird issue though which might be due to the hardware I am using. According to its [website(http://www.lcdwiki.com/7inch_HDMI_Display-C#Product_Description) The software resolution is different from the hardware resolution. When I set the viewport config to 1920*1080 the screen renders correct but the touch events do not trigger in the correct location. I am not sure how to fix this other than to buy different hardware.

**Comment by koenusz** [comment]
I think the solution should be something with configuring the calibration:
https://hexdocs.pm/scenic_driver_nerves_touch/Scenic.Driver.Nerves.Touch.html
https://www.ti.com/lit/an/slyt277/slyt277.pdf

my configuration right now is:
```
  drivers: [
    [
      module: Scenic.Driver.Local,
      window: [title: "Testing Scenic"],
      position: [scaled: true, centered: true, orientation: :normal],
      calibration: [{"FT5406 memory based driver", {{1.55, 0, 0}, {0, 1.8, 0}}}]
    ]
  ]

```
But is does not seem to do anything. I suspect it is because the driver name is incorrect (I might be completely incorrect about this). My screen is an hdmi screen and as such might require other drivers than the standard rpi screen.

**Comment by ringlej** [comment]
For our embedded device, we [tslib](https://github.com/libts/tslib) for calibration. It provides a virtual touch driver that has been calibrated using the hw touch driver. I then use the scenic_driver_local `input_blacklist: ["resistive-adc-touch"]` to disable hw touch driver, since we now only want touch events from the virtual touch driver provided by tslib. You can use `InputEvent.enumerate/0` to get a list of input devices and find out the name of the hw touch driver that needs to be disabled if you use tslib.

We then delay starting the scenic driver until the touch screen calibration file has been created and the virtual tslib driver has started.

For this solution, you'll need to add `BR2_PACKAGE_TSLIB=y` to your nerves_system_rpi4. (Note, that I haven't tried this on rpi, but I think it should work)

This is how we are integrating with tslib on our device:
```elixir
defmodule EC2K.Display do
  @moduledoc """
  Driver for our touchscreen display.

  We use tslib to provide a normalized touchscreen events in screen coordinates.

  The Linux raw-adc-touchscreen driver provides the x/y coordinates in raw adc counts.
  The tslib provides the mechanism for translating raw adc touch coordinates to screen coordinates.
  However, to be able to provide this translation, a calibration process is required.

  A calibration process will start if the /data/pointercal file is missing
  This calibration comes in two parts:
    1. Calibration
       During calibration, five crosshairs are displayed to the user at fixed points:
        * Upper left
        * Upper right
        * Lower right
        * Lower left
        * Center
      This generates a /tmp/pointercal calibration file based on where the user touched the screen.
    2. Validation
      During validation, a number of crosshairs (@validation_touches) are displayed to the user at
      random screen locations. When the user touches each crosshair, it will validate that the screen
      coordinates for the touch event closely match the location where the crosshair was rendered on
      the screen. If there is a failure, the calibration process is restarted.

  Once there is a valid /data/pointercal file, the ts_uinput daemon is started that will provide a new
  input event in /dev/input
  """

  use GenServer

  @tslib_calibfile "/data/pointercal"
  @temp_calibfile "/tmp/pointercal"

  @recalibration_timeout 30
  @min_ms_between_touches 100
  @validation_boundary_threshold 25
  @validation_touches 3
  @validation_min_distance_from_edge 30

  def start_link(_args) do
    GenServer.start_link(__MODULE__, nil)
  end

  @impl GenServer
  def init(_) do
    timeout =
      case File.exists?(@tslib_calibfile <> ".old") do
        true -> @recalibration_timeout
        false -> 0
      end

    case File.exists?(@tslib_calibfile) do
      false -> send(self(), {:calibrate, timeout})
      true -> send(self(), :ready)
    end

    {:ok, nil}
  end

  @impl GenServer
  def handle_info({:calibrate, timeout}, state) do
    {_stdout, exit_code} =
      MuonTrap.cmd(
        "ts_calibrate",
        ["--min_interval", "#{@min_ms_between_touches}", "--start_prompt", "#{timeout}"],
        env: [{"TSLIB_CALIBFILE", @temp_calibfile}]
      )

    case exit_code do
      0 ->
        File.rm(@tslib_calibfile <> ".old")
        send(self(), :validate_calibration)

      _ ->
        send(self(), :ready)
    end

    {:noreply, state}
  end

  @impl GenServer
  def handle_info(:validate_calibration, state) do
    {_stdout, exit_code} =
      MuonTrap.cmd(
        "ts_calibrate",
        [
          "--min_interval",
          "#{@min_ms_between_touches}",
          "--validate",
          "--boundary",
          "#{@validation_boundary_threshold}",
          "--loop",
          "#{@validation_touches}",
          "--border",
          "#{@validation_min_distance_from_edge}"
        ],
        env: [{"TSLIB_CALIBFILE", @temp_calibfile}]
      )

    with 0 <- exit_code,
         :ok = File.cp(@temp_calibfile, @tslib_calibfile),
         :ok = File.rm(@temp_calibfile) do
      send(self(), :ready)
    else
      _error ->
        send(self(), {:calibrate, 0})
    end

    {:noreply, state}
  end

  @impl GenServer
  def handle_info(:ready, state) do
    main_viewport_config = Application.get_env(:ec2k_firmware, :viewport)

    children = [
      {MuonTrap.Daemon,
       [
         "ts_uinput",
         [],
         [
           env: [
             {"TSLIB_CALIBFILE", @tslib_calibfile},
             {"TSLIB_CONFFILE", "/etc/ts.conf"},
             {"TSLIB_FBDEVICE", "/dev/fb0"},
             {"TSLIB_PLUGINDIR", "/usr/lib/ts"},
             {"TSLIB_TSDEVICE", "/dev/input/event0"}
           ]
         ]
       ]}
    ]

    {:ok, pid} = Supervisor.start_link(children, strategy: :one_for_one)

    wait_for_devinput()

    Supervisor.start_child(pid, {Scenic, [main_viewport_config]})

    {:noreply, state}
  end

  defp wait_for_devinput do
    InputEvent.enumerate()
    |> Enum.find(fn {_dev_path, info} -> info.name == "ts_uinput" end)
    |> case do
      nil ->
        Process.sleep(100)
        wait_for_devinput()

      _ ->
        :ok
    end
  end
end
```

**Comment by crertel** [comment]
@koenusz sorry if I'm reading the thread wrong, but did @ringlej get you sorted? Can I close this?

**Comment by koenusz** [comment]
I did not have the chance to work further on this project but i think you can close the issue. Thank you all.
