### ISSUE TITLE
Adding support for direct framebuffer rendering

### ISSUE THREAD

**Issue by ringlej** [ScenicFramework/scenic_driver_local#25]
We have an embedded device that does not have hardware opengl support. The mesa3d swrast dri driver is way to slow and quite frankly adding all the library support for opengl to our embedded device is very bloated and adds significant footprint to what we have available to use for the rootfs on our nand flash.

I spent some time studying the interface between `scenic` and `scenic_driver_local`
Most of the primatives scenic interface is defined in [scenic/script.ex](https://github.com/ScenicFramework/scenic/blob/main/lib/scenic/script.ex#L264-L346)
The handling of this on `scenic_driver_local` side of this is in c_src/script.c [render_script()](https://github.com/ScenicFramework/scenic_driver_local/blob/main/c_src/script.c#L262)
Currently, this is very nanovg centric which is tied to opengl.
I propose to do the following:
1. Abstract out the nanovg interface calls. Some thing like:
```c
enum scenic_op { // to match op_* constants in https://github.com/ScenicFramework/scenic/blob/main/lib/scenic/script.ex#L176
  scenic_op_draw_line = 1,
  ...
};

typedef struct {
  void* user_ptr;
  void (*draw_line)(void* uptr, float x0, float y0, float x1, float y1, bool stroke);
  ...
} scenic_ops_t;

typedef struct {
  bool              keep_going;
  uint32_t          input_flags;
  float             last_x;
  float             last_y;
  int               root_script;
  void*             p_tx_ids;
  void*             p_fonts;
  // Moving to scenic_ops_t.user_ptr: NVGcontext* p_ctx;
  scenic_ops_t* p_scenic_ops;
  float           global_tx[6];
  float           cursor_tx[6];
  float           cursor_pos[2];
  uint32_t          f_show_cursor;
} driver_data_t;

typedef struct {
  // internal data tracking
  int width;
  int height;
  float ratio;
  // Moving to scenic_ops.user_ptr: NVGcontext* p_ctx;
  scenic_ops_t scenic_ops;
} device_info_t;
```

drm.c:
```c
int init_egl( const device_opts_t* p_opts, device_info_t* p_info)
{
  ...

#ifdef SCENIC_GLES2
  p_info->scenic_ops.user_ptr = nvgCreateGLES2( nvg_opts );
#else
  p_info->scenic_ops.user_ptr = nvgCreateGLES3( nvg_opts );
#endif
  p_info->scenic_ops.draw_line = nvg_draw_line;
}

void nvg_draw_line(NVGcontext* p_ctx, float x0, float y0, float x1, float y1, bool stroke)
{
  nvgBeginPath(p_ctx);
  nvgMoveTo(p_ctx, x0, y0);
  nvgLineTo(p_ctx, x1, y1);
  if (stroke) nvgStroke(p_ctx);
}
```

comms.c:
```c
void render_script( sid_t id, const device_data_t* p_data)
{
 // get the script

  script_t* p_script = get_script( id );
  if ( !p_script ) {
    return;
  }

  // track the state pushes
  int push_count = 0;

  // setup
  void* p = p_script->script.p_data;
  int i = 0;

  while ( i < p_script->script.size ) {
    int op = get_uint16(p, i);
    int param = get_uint16(p, i + 2);
    i += 4;

    switch( op ) {
      case scenic_op_draw_line:
        p_data->p_scenic_ops->draw_line(p_data->p_scenic_ops->user_ptr,
                                        get_float(p, i), get_float(p, i+4),
                                        get_float(p, i+8), get_float(p, i+12),
                                        (param & 2));
        i += 16;
        break;
  ...
}
```
2. After the above abstraction is in place, I can then add an implementation that uses [cairo](https://cairographics.org/tutorial/) for the primitive operations and then rendering to the framebuffer device directly (/dev/fb0)

I am now working on this, but wanted to check that this seems like a reasonable approach

**Comment by amclain** [comment]
Considering `scenic_driver_local` is the `glfw` implementation, it would probably be better to make a new driver like `scenic_driver_cairo` that uses the cairo library. @crertel may have some thoughts to add since he recommended cairo.

**Comment by crertel** [comment]
I think @amclain has the correct idea--we probably want a dedicated `scenic_driver_cairo`.

Honestly, my suggestion would be to do something like:

1. Document the script binary format, since that's we use. This will help everyone.
2. Fork the `scenic_driver_local` into `scenic_driver_debug`. Replace all the rendering/nanovg/glfw code with `printf` to show what is attempting to render.
3. Fork `scenic_driver_debug` into `scenic_driver_cairo`, and implement 2D rendering that way.

That's my rough guess, but I totes recognize that that's the "this is ideal from what would probably benefit scenic and others" standpoint and is a bit more work than just forking to cairo directly. Thoughts?

**Comment by crertel** [comment]
Here's a rough stab at (2) from above: https://github.com/ScenicFramework/scenic_driver_debug/pull/1 . Doesn't build yet, but I figured it'd be good to get some feedback to see what people think.

**Comment by ringlej** [comment]
I'm unable to see that repo ☹️

**Comment by ringlej** [comment]
Something I did to help with debugging as I went along is to make log_info and friends printf-like with variadic arguments:
```c
//---------------------------------------------------------
void logv(uint32_t cmd, const char* msg, va_list args)
{
  char* output;
  vasprintf(&output, msg, args);
  uint32_t msg_len = strlen(output);
  uint32_t cmd_len = ntoh_ui32(msg_len + sizeof(uint32_t));

  write_exact((byte*) &cmd_len, sizeof(uint32_t));
  write_exact((byte*) &cmd, sizeof(uint32_t));
  write_exact((byte*) output, msg_len);
}

void send_puts(const char* msg, ...)
{
  va_list args;
  va_start(args, msg);

  logv(MSG_OUT_PUTS, msg, args);
}

//---------------------------------------------------------
void log_info(const char* msg, ...)
{
  va_list args;
  va_start(args, msg);

  logv(MSG_OUT_INFO, msg, args);
}

//---------------------------------------------------------
void log_warn(const char* msg, ...)
{
  va_list args;
  va_start(args, msg);

  logv(MSG_OUT_WARN, msg, args);
}

//---------------------------------------------------------
void log_error(const char* msg, ...)
{
  va_list args;
  va_start(args, msg);

  logv(MSG_OUT_ERROR, msg, args);
}
```

**Comment by crertel** [comment]
@ringlej should be visible now!
