### ISSUE TITLE
`gl_helpers.c` fatal error: 'GLES3/gl3.h' file not found

### ISSUE THREAD

**Issue by GPrimola** [ScenicFramework/scenic_driver_local#41]
I'm getting the following error when trying to compile `scenic_driver_local` on MacOS Ventura 13.5.

```sh
mix deps.compile scenic_driver_local
==> scenic_driver_local
SCENIC_LOCAL_TARGET: glfw
cc -O3 -std=c99 `pkg-config --static --cflags glfw3 glew` -fPIC -Ic_src -Ic_src/device -Ic_src/font -Ic_src/image -Ic_src/nanovg -Ic_src/scenic -Ic_src/tommyds/src -o /Users/giolucas/projects/nerves_projects/nerv_os/_build/dev/lib/scenic_driver_local/priv/scenic_driver_local  c_src/device/glfw.c c_src/device/gl_helpers.c c_src/nanovg/nanovg.c c_src/font/font.c c_src/font/nvg_font_ops.c c_src/image/image.c c_src/image/nvg_image_ops.c c_src/tommyds/src/tommyhashlin.c c_src/tommyds/src/tommyhash.c c_src/scenic/comms.c c_src/scenic/ops/scenic_ops.c c_src/scenic/ops/script_ops.c c_src/scenic/script.c c_src/scenic/unix_comms.c c_src/scenic/utils.c c_src/scenic/ops/nvg_script_ops.c c_src/main.c `pkg-config --static --libs glfw3 glew` -framework Cocoa -framework OpenGL -Wno-deprecated
c_src/device/gl_helpers.c:6:12: fatal error: 'GLES3/gl3.h' file not found
    #include <GLES3/gl3.h>
             ^~~~~~~~~~~~~
```

I googled a little bit and it seems on MacOS the OpenGL3 include `gl3.h` is not under `GLES3`, but in `OpenGL`, so on `c_src/device/gl_helpers.c:6:12` the include should be: `#include <OpenGL/gl3.h>`.

Is this any kind of misconfiguration on my end?

**Comment by iwarshak** [comment]
@GPrimola same issue here. find a fix?

**Comment by GPrimola** [comment]
@iwarshak yes! I think it's already fixed on main branch, try to sync it and it should work. I haven't tried it yet so I can't be sure, but the code seems fine: https://github.com/ScenicFramework/scenic_driver_local/blob/6af7fb4fd8e7ff3f428d60b7781836056f7c184a/c_src/device/gl_helpers.c#L6-L10

**Comment by iwarshak** [comment]
@GPrimola are you able to compile this for a raspberry pi though? this is where I am seeing this issue (host development works fine for me)

**Comment by seb3s** [comment]
Same here
Able to compile for host (apple M1 chip) but not for a rpi3a target.
