### ISSUE TITLE
drm mode is broken

### ISSUE THREAD

**Issue by axelson** [ScenicFramework/scenic_driver_local#47]
drm mode appears to have broken in https://github.com/ScenicFramework/scenic_driver_local/pull/27

There appear to be at least one of the issues that was fixed for bcm in https://github.com/ScenicFramework/scenic_driver_local/pull/46, namely that `p_ctx` is still referred to instead of `v_ctx`

**Comment by crertel** [comment]
@axelson is this still the case sir, or can I close this?

**Comment by crertel** [comment]
@axelson I'm going to go ahead and close this, since we merged in the cairo support and hopefully that'll fix this. Let me know if you want me to reopen and try again.
